### ISSUE TITLE
Chore : Images report-en.png + rest of images in subfolder are marked for deletion

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/systeme-conception#58]
Hi Folks, 

These files have been marked for deletion. Is there any additional context we should be aware of?

report-en.png
service-standards-page-en.jpg
sig-en.png
site-footer-en.png
site-search-en.png
theme-menu-flyout-en.png
theme-page-en.jpg

**Comment by delisma** [comment]
Fixed with a8833fb3bad46f04d829475c49d18a7bddd99847
