### ISSUE TITLE
chore: Delete css/USE-EN-REPO

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/systeme-conception#74]
css/USE-EN-REPO

this file has been marked for deletion

**Comment by delisma** [comment]
Use of custom CSS should be re-evaluated.
For the moment a solution like Symbolic Link or Submodule are explored to sync the CSS files

**Comment by delisma** [comment]
To be synced
- alpha-beta-banner.css 
- custom.css
- navigation.css
- do-dont.css
- new-alerts.css
- checkbox-radio.css
- guidance-draft.css
- provisional-alerts.css
- colour-cards.css
- iframe.css
- split-h1.css
- component-presentation.css
- ip.css
- ./beta:
  - mr-bullets.css
  - social-media.css
  - theme-topic.css
