### ISSUE TITLE
Chore : Rename `ministerial-profile-fr-cropped.jpg`

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/systeme-conception#77]
images/ministerial-profile-fr-cropped.jpg

The following file has been marked to be moved to GC-Proto Experimental

GC Proto link : https://github.com/gc-proto/experimental/issues/16

**Comment by delisma** [comment]
The file has been identified to be rename instead of moved. I'm suggesting `profil-ministeriel-recadree.jpg`
